name: salva
description: A note-taking & to-do app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2
  android_intent_plus: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  #  flutter_native_splash: ^2.0.1+1

  #flutter_native_splash:
  #  color: "#303030"
  #  image: assets/icon.png
  #  android: true
  #  ios: false
  #  web: false
  #  android_gravity: center
  #  fullscreen: true

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/Manrope-Light.ttf
